spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DB_REST?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 88888888
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBdialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: create